<?php

use Magento\Catalog\Model\Product;

?>
<style>
    .minicart-wrapper{
        display: none;
    }

    #Gsframe {
        height: 1300px;
    }

    @media only screen and (min-width: 630px) and (max-width: 1026px) {
        #Gsframe {
            height: 1900px;
        }
    }

    @media only screen and (min-width: 600px) and (max-width: 797px) {
        #Gsframe {
            height: 1900px;
        }
    }

    @media only screen and (min-width: 510px) and (max-width: 629px) {
        #Gsframe {
            height: 2000px;
        }
    }

    @media only screen and (max-width: 509px) {
        #Gsframe {
            height: 1900px;
        }
    }
</style>
<iframe id="Gsframe" name="Gsframe" style="width: 100%;" frameborder="0" scrolling="auto" allowtransparency="true">
</iframe>
<form name="frmPP" id="frmPP" method="post" action="https://globalshopex.com/iframe4.0/internationalcheckout.aspx"
      target="Gsframe">
    <input type="hidden" name="MerchantID" value="<?= $block->escapeHtml($block->getMerchantID()) ?>"/>
    <?php
    /*if (Mage::helper('core')->isModuleEnabled('Gsx_Localization')) {
    echo '<input type="hidden" name="Destination" value="CA">';
    echo '<input type="hidden" name="Currency" value="CAD">';
    /*}*/
    ?>
    <input name='Language' type='hidden' value='SP'>
    <?php if ($block->isClearCartEnable()) { ?>
        <input type="hidden" name="URLCart"
               value="<?= $block->escapeHtml($block->getBaseUrl()) .
                "globalshopex/gsxemptycart/index?quoteid=" . $block
                ->escapeHtml($block->cart->getQuote()->getId()); ?>"/>
        <?php
    }
    $imgWidth = 75;
    $imgHeight = 75;

    $GSX_restriction_attribute = $block->getNameRestrictedItem();

    $session = $block->cart;
    // $inputsGsxCart = "";
    $i = 1;
    $objManager = \Magento\Framework\App\ObjectManager::getInstance();
    foreach ($session->getQuote()->getAllVisibleItems() as $item) {
        $optionsGSX = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct());
        $item_ID = $item->getProductId();
        //$_Product = $objManager->get('Magento\Catalog\Model\Product')->load($item_ID);
        $_Product = $objManager->create(Product::Class)->load($item_ID);
        // if (Mage::helper('gsx_globalshopex')->validateProductByName($this
        // ->buildItemDescription($item))) { //skincarebyalana
        $ProductPrice = $item->getPrice();
        $ProductPrice = (stristr($ProductPrice, "."))?
        substr($ProductPrice, 0, strrpos($ProductPrice, ".") + 3):
        $ProductPrice;
        $ProductWeight = $_Product->getWeight();
        $ProductWeight = substr($ProductWeight, 0, strrpos($ProductWeight, ".") + 3);

        if ($ProductWeight == "") {
            $ProductWeight = "0";
        }
        ?>
        <input type="hidden" name="ProductSKU<?= $block->escapeHtml($i) ?>"
         value="<?= $block->escapeHtml($item->getSku()) ?>"/>\n

        <input type="hidden" name="ProductDesc<?= $block->escapeHtml($i) ?>" value="<?= $block
        ->escapeHtml(htmlentities($block->buildItemDescription($item))) ?>"/>\n

        <input type="hidden" name="ProductLink<?= $block->escapeHtml($i) ?>"
         value="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"/>\n

        <input type="hidden" name="ProductQty<?= $block->escapeHtml($i) ?>"
         value="<?= $block->escapeHtml($item->getQty()) ?>"/>\n

        <input type="hidden" name="ProductPrice<?= $block->escapeHtml($i) ?>"
         value="<?= $block->escapeHtml($ProductPrice) ?>"/>\n

        <input type="hidden" name="ProductSize<?= $block->escapeHtml($i) ?>"
         value="<?= $block->escapeHtml($block->getSize($item)) ?>"/>\n

        <input type="hidden" name="ProductColor<?= $block->escapeHtml($i) ?>"
         value="<?= $block->escapeHtml($block->getColor($item)) ?>"/>\n

        <input type="hidden" name="ProductWeight<?= $block->escapeHtml($i) ?>"
         value="<?= $block->escapeHtml($ProductWeight) ?>"/>\n
        <?php
        if ($item->getCountry() != "") {
            ?>
            <input type="hidden" name="ProductCountry<?= $block->escapeHtml($i) ?>"
             value="<?= $block->escapeHtml($item->getCountry()) ?>"/>\n
            <?php
        }
        if ($item->getBrand($item) != "") {
            ?>
            <input type="hidden" name="ProductBrand<?= $block->escapeHtml($i) ?>"
             value="<?= $block->escapeHtml($block->getBrand($item)) ?>"/>\n
            <?php
        }

//            if ($GSX_restriction_attribute != "") {
//                $attributes = Mage::getResourceModel('eav/entity_attribute_collection')
//                        ->setEntityTypeFilter($_Product->getResource()->getTypeId())
//                        ->addFieldToFilter('attribute_code', $GSX_restriction_attribute)
//                        ->load(false);
//
//                $attribute = $attributes->getFirstItem()->setEntity($_Product->getResource());
//                $manufac = $attribute->getSource()->getAllOptions(false);
//                foreach ($manufac as $man) {
//                    $intshiping[$man['value']] = $man['label'];
//                }
//                if ($_Product->getData($GSX_restriction_attribute) == '1')
//                    $inputsGsxCart .= "<input type=\"hidden\" name=\"Restricted$i\" value='1'/>\n";
//            }
        ?>
        <input type="hidden" name="ProductImage<?= $block->escapeHtml($i) ?>" value="<?= $block
        ->escapeHtml($block->getProductThumbnail($item)) ?>"/>\n

        <input type="hidden" name="ProductOptions<?= $block->escapeHtml($i) ?>" value="<?= $block
        ->escapeHtml(htmlentities(json_encode($optionsGSX))) ?>"/>\n
        <?php
        $i++;
        // } //skincarebyalana
    }
    // echo $inputsGsxCart;
    $GSX_totals = $session->getQuote()->getData();
    //print_r($GSX_totals);
    $coupon_code = $GSX_totals['coupon_code'];
    $discount = $GSX_totals['subtotal'] - $GSX_totals['subtotal_with_discount'];
    $perc = ($discount * 100) / $GSX_totals['subtotal'];
    $perc = round($perc, 2);
    ?>

    <?php
    if ($coupon_code == "" && $discount>0) {
        $coupon_code = "ItlStandard";
    }

    if ($coupon_code != "") {
        ?>
        <input type="hidden" name="ODiscount" value="<?= $block->escapeHtml($perc) ?>"/>
        <input type="hidden" name="ODiscCode" value="<?= $block->escapeHtml($coupon_code) ?>"/>
        <input type="hidden" name="ODiscPerc" value="1"/>
        <?php
    }
    ?>
    <input type="hidden" name="LocalShippingEXP" value="<?= $block->escapeHtml($block->getLocalshippingEXP()) ?>" />
    <input type="hidden" name="LocalShipping" value="<?= $block->escapeHtml($block->getLocalshipping()) ?>" />
    <!-- echo $block->getLocalshippingEXP();
    echo $block->getLocalshipping(); -->
</form>
<iframe id="GsEndframe" name="GsEndframe" style="display: none;" frameborder="0" scrolling="auto"
        allowtransparency="true"></iframe>
<form style="display: none;" name="frmGoToEnd" id="frmGoToEnd" method="post"
      action="/globalshopex/gsxemptycart/index" target="GsEndframe">
    <button id="btnSendToEnd" title="<?= $block->escapeHtml(__("International Checkout")) ?>"
            class="<?= $block->escapeHtml($block->getNamebuttonCssClassName()) ?> action primary checkout" type="submit"
            style="<?= $block->escapeHtml($block->getStyleExtend()) ?>">
            <span>
                <span><?= $block->escapeHtml($block->buttonTextInternationalCustomer()) ?></span>
            </span>
    </button>
</form>
<script>
    document.getElementById('frmPP').submit();
    function sendToEnd() {
        //document.getElementById('frmGoToEnd').submit();
        document.getElementById('btnSendToEnd').click();
    }
    
</script>