<br>
<div class="account-login">
    <div class="col2-set">
        <div class="col-1 new-users">
            <div class="content" style="min-height: 45px">
                <h2>International Checkout</h2>

                <p>Tracking Globalshopex.com</p>
            </div>
            <div class="buttons-set">
                <form action="<?= $block->escapeUrl($block->getBaseUrl()) ?>globalshopex/tracking/index" method="post"
                      id="GSXLogin-form">
                    <button type="submit" type="button" title="Tracking Globalshopex.com click here" class="button">
                            <span>
                                <span>Click here</span>
                            </span>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
